# Generated by Django 3.1.1 on 2021-01-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tools_User', '0007_jk'),
    ]

    operations = [
        migrations.AddField(
            model_name='jk',
            name='user',
            field=models.CharField(default='', max_length=100, verbose_name='添加用户'),
        ),
    ]
